version: '3.8'

services:
  course-frontend:
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    container_name: course-frontend-container
    image: course-frontend:v2
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./src:/app/src
    ports:
      - 80:80
      - 3000:3000
